spring:
  profiles:
    active: local
    group:
      local: local, common
      blue: blue, common
      green: green, common
server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local
server:
  port: 8080
  serverAddress: localhost
serverName: local_server

---

spring:
  config:
    activate:
      on-profile: blue
server:
  port: 8080
  serverAddress: 43.201.215.174
serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green
server:
  port: 8081
  serverAddress: 43.201.215.174
serverName: green_server

---

spring:
  config:
    activate:
      on-profile: common
  upload:
    path: C:\Users\hachi\IdeaProjects\file-save\
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deterior?serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jwt:
    secret: 5e8ab1a366a94e6c91956135f0383671bbb5955dfe7c758b7018bfe8b93d893e
  mail:
    host: smtp.gmail.com
    port: 587
    username: sonickim6679@gmail.com
    password: cozq njji eles osma
    auth: true
    timeout: 5000
    auth-code-expiration-millis: 1800000
    properties:
      mail:
        smtp:
          starttls:
            enable: true
