spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deterior?serverTimezone=Asia/Seoul
    username: root
    password: root
  jwt:
    secret: 5e8ab1a366a94e6c91956135f0383671bbb5955dfe7c758b7018bfe8b93d893e
  mail:
    host: smtp.gmail.com
    port: 587
    username: sonickim6679@gmail.com
    password: cozq njji eles osma
    auth: true
    timeout: 5000
    auth-code-expiration-millis: 1800000
    properties:
      mail:
        smtp:
          starttls:
            enable: true